# Generated by Django 3.2.3 on 2021-06-04 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=40)),
                ('other', models.CharField(max_length=100)),
                ('fieldof_study', models.CharField(max_length=100)),
                ('graduation_year', models.CharField(max_length=30)),
                ('marital', models.CharField(max_length=100)),
                ('children', models.CharField(max_length=20)),
                ('immigrant_status', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=40)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
