# Generated by Django 3.2.3 on 2021-06-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaid',
            name='int_identity',
            field=models.TextField(default='international'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaid',
            name='reason',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
